#!/usr/bin/env bash

MPVSOCKET=/tmp/mpv-append-socket

# Fix freetube where $1 is empty
if [ "$#" -eq 2 ]; then
   video="$2"
else
   video="$1"
fi

# See if MPV is already running
if [ ! -e "${MPVSOCKET}" ]; then
  # mpv is not running
  /usr/bin/mpv --no-terminal --input-ipc-server="${MPVSOCKET}" "$video" && rm "${MPVSOCKET}" &

  # Wait for mpv to be up before moving on to adding anything else to playlist
  while [ ! -e "${MPVSOCKET}" ]; do
    sleep 1
  done

else
  # mpv is running, so add stuff to playlist
  echo "loadfile \"$video\" append-play" | socat - "${MPVSOCKET}"
fi
